site_name: Spot@MHS
site_url: https://purelyboba.github.io/spot@mhs
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: purple
      accent: purple
    - scheme: slate 
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode  
      primary: purple
      accent: lime
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select
    - content.code.annotate
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
 - index.md
 - Spot Fundamentals:
    - spot-fundamentals/spot-fundamentals.md
    - spot-fundamentals/unboxing-spot.md
    - spot-fundamentals/anatomy-of-spot.md
    - spot-fundamentals/power-management.md
    - spot-fundamentals/startup-shutdown.md
    - spot-fundamentals/storage-safety.md
 - Locomotion with Controller:
    - locomotion-with-controller/locomotion-with-controller.md
    - locomotion-with-controller/operational-safety.md
    - locomotion-with-controller/controller-layout.md
    - locomotion-with-controller/self-righting-spot.md
    - locomotion-with-controller/posing-spot.md
    - locomotion-with-controller/walking-spot.md
    - locomotion-with-controller/arm-and-claw.md
 - Coding Spot:
    - coding-spot/coding-spot.md
    - coding-spot/spot-coding-basics.md
    - coding-spot/startup-and-movement.md
 - OpenPayload:
    - open-payload/open-payload.md
copyright: 
  © 2024 <a href="https://mhs.millburn.org/"  target="_blank" rel="noopener">Millburn Robotics</a>.
  Special thanks to Boston Dynamics.
